/**
 * Complete language list from JW.org
 * Auto-generated language codes and names
 */

export interface Language {
    code: string;
    name: string;
    vernacularName: string;
    script: string;
    direction: 'ltr' | 'rtl';
    isSignLanguage: boolean;
}

export const LANGUAGES: Language[] = [
    { code: 'en-US', name: 'English', vernacularName: 'English', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'es-ES', name: 'Spanish', vernacularName: 'Español', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'tl-PH', name: 'Filipino (Tagalog)', vernacularName: 'Tagalog', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'fr-FR', name: 'French', vernacularName: 'Français', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'de-DE', name: 'German', vernacularName: 'Deutsch', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ja-JP', name: 'Japanese', vernacularName: '日本語', script: 'JAPANESE', direction: 'ltr', isSignLanguage: false },
    { code: 'ko-KR', name: 'Korean', vernacularName: '한국어', script: 'KOREAN', direction: 'ltr', isSignLanguage: false },
    { code: 'zh-CN', name: 'Chinese (Simplified)', vernacularName: '中文简体', script: 'CHINESE', direction: 'ltr', isSignLanguage: false },
    { code: 'pt-BR', name: 'Portuguese (Brazil)', vernacularName: 'Português (Brasil)', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ar', name: 'Arabic', vernacularName: 'العربية', script: 'ARABIC', direction: 'rtl', isSignLanguage: false },
    { code: 'hi', name: 'Hindi', vernacularName: 'हिन्दी', script: 'DEVANAGARI', direction: 'ltr', isSignLanguage: false },
    { code: 'ru', name: 'Russian', vernacularName: 'русский', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'it', name: 'Italian', vernacularName: 'Italiano', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'nl', name: 'Dutch', vernacularName: 'Nederlands', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'pl', name: 'Polish', vernacularName: 'polski', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'vi', name: 'Vietnamese', vernacularName: 'Tiếng Việt', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'th', name: 'Thai', vernacularName: 'ไทย', script: 'THAI', direction: 'ltr', isSignLanguage: false },
    { code: 'id', name: 'Indonesian', vernacularName: 'Indonesia', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ms', name: 'Malay', vernacularName: 'Melayu', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'tr', name: 'Turkish', vernacularName: 'Türkçe', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'uk', name: 'Ukrainian', vernacularName: 'українська', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'el', name: 'Greek', vernacularName: 'Ελληνική', script: 'GREEK', direction: 'ltr', isSignLanguage: false },
    { code: 'cs', name: 'Czech', vernacularName: 'čeština', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'sv', name: 'Swedish', vernacularName: 'Svenska', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ro', name: 'Romanian', vernacularName: 'Română', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'hu', name: 'Hungarian', vernacularName: 'magyar', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'da', name: 'Danish', vernacularName: 'Dansk', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'fi', name: 'Finnish', vernacularName: 'suomi', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'no', name: 'Norwegian', vernacularName: 'Norsk', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'he', name: 'Hebrew', vernacularName: 'עברית', script: 'HEBREW', direction: 'rtl', isSignLanguage: false },
    { code: 'fa', name: 'Persian (Farsi)', vernacularName: 'فارسی', script: 'ARABIC', direction: 'rtl', isSignLanguage: false },
    { code: 'bn', name: 'Bengali', vernacularName: 'বাংলা', script: 'BENGALI', direction: 'ltr', isSignLanguage: false },
    { code: 'ta', name: 'Tamil', vernacularName: 'தமிழ்', script: 'TAMIL', direction: 'ltr', isSignLanguage: false },
    { code: 'te', name: 'Telugu', vernacularName: 'తెలుగు', script: 'TELUGU', direction: 'ltr', isSignLanguage: false },
    { code: 'mr', name: 'Marathi', vernacularName: 'मराठी', script: 'DEVANAGARI', direction: 'ltr', isSignLanguage: false },
    { code: 'gu', name: 'Gujarati', vernacularName: 'ગુજરાતી', script: 'GUJARATI', direction: 'ltr', isSignLanguage: false },
    { code: 'kn', name: 'Kannada', vernacularName: 'ಕನ್ನಡ', script: 'KANNADA', direction: 'ltr', isSignLanguage: false },
    { code: 'ml', name: 'Malayalam', vernacularName: 'മലയാളം', script: 'MALAYALAM', direction: 'ltr', isSignLanguage: false },
    { code: 'pa', name: 'Punjabi', vernacularName: 'ਪੰਜਾਬੀ', script: 'GURMUKHI', direction: 'ltr', isSignLanguage: false },
    { code: 'ur', name: 'Urdu', vernacularName: 'اردو', script: 'ARABIC', direction: 'rtl', isSignLanguage: false },
    { code: 'sw', name: 'Swahili', vernacularName: 'Kiswahili', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'am', name: 'Amharic', vernacularName: 'አማርኛ', script: 'ETHIOPIC', direction: 'ltr', isSignLanguage: false },
    { code: 'my', name: 'Myanmar (Burmese)', vernacularName: 'မြန်မာ', script: 'MYANMAR', direction: 'ltr', isSignLanguage: false },
    { code: 'km', name: 'Cambodian (Khmer)', vernacularName: 'ខ្មែរ', script: 'CAMBODIAN', direction: 'ltr', isSignLanguage: false },
    { code: 'lo', name: 'Laotian', vernacularName: 'ລາວ', script: 'LAOTIAN', direction: 'ltr', isSignLanguage: false },
    { code: 'si', name: 'Sinhala', vernacularName: 'සිංහල', script: 'SINHALA', direction: 'ltr', isSignLanguage: false },
    { code: 'ne', name: 'Nepali', vernacularName: 'नेपाली', script: 'DEVANAGARI', direction: 'ltr', isSignLanguage: false },
    { code: 'bg', name: 'Bulgarian', vernacularName: 'български', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'hr', name: 'Croatian', vernacularName: 'hrvatski', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'sr', name: 'Serbian', vernacularName: 'српски', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'sk', name: 'Slovak', vernacularName: 'slovenčina', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'sl', name: 'Slovenian', vernacularName: 'slovenščina', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'et', name: 'Estonian', vernacularName: 'eesti', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'lv', name: 'Latvian', vernacularName: 'latviešu', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'lt', name: 'Lithuanian', vernacularName: 'lietuvių', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'sq', name: 'Albanian', vernacularName: 'shqip', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'mk', name: 'Macedonian', vernacularName: 'македонски', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'ka', name: 'Georgian', vernacularName: 'ქართული', script: 'GEORGIAN', direction: 'ltr', isSignLanguage: false },
    { code: 'hy', name: 'Armenian', vernacularName: 'Հdelays', script: 'ARMENIAN', direction: 'ltr', isSignLanguage: false },
    { code: 'az', name: 'Azerbaijani', vernacularName: 'Azərbaycan', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'kk', name: 'Kazakh', vernacularName: 'қазақ', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'uz', name: 'Uzbek', vernacularName: "O'zbek", script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ky', name: 'Kirghiz', vernacularName: 'кыргыз', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'tg', name: 'Tajik', vernacularName: 'тоҷикӣ', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'tk', name: 'Turkmen', vernacularName: 'Türkmen', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'mn', name: 'Mongolian', vernacularName: 'монгол', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'af', name: 'Afrikaans', vernacularName: 'Afrikaans', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'zu', name: 'Zulu', vernacularName: 'isiZulu', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'xh', name: 'Xhosa', vernacularName: 'isiXhosa', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'st', name: 'Sesotho', vernacularName: 'Sesotho', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'tn', name: 'Setswana', vernacularName: 'Setswana', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'sn', name: 'Shona', vernacularName: 'chiShona', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'yo', name: 'Yoruba', vernacularName: 'Yorùbá', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ig', name: 'Igbo', vernacularName: 'Igbo', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ha', name: 'Hausa', vernacularName: 'Hausa', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'rw', name: 'Kinyarwanda', vernacularName: 'Ikinyarwanda', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'mg', name: 'Malagasy', vernacularName: 'Malagasy', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ny', name: 'Chichewa', vernacularName: 'Chichewa', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'so', name: 'Somali', vernacularName: 'Soomaali', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ga', name: 'Irish', vernacularName: 'Gaeilge', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'cy', name: 'Welsh', vernacularName: 'Cymraeg', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'eu', name: 'Basque', vernacularName: 'Euskara', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'gl', name: 'Galician', vernacularName: 'Galego', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ca', name: 'Catalan', vernacularName: 'català', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'is', name: 'Icelandic', vernacularName: 'íslenska', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'mt', name: 'Maltese', vernacularName: 'Malti', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'lb', name: 'Luxembourgish', vernacularName: 'Lëtzebuergesch', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'be', name: 'Belorussian', vernacularName: 'беларуская', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'ceb', name: 'Cebuano', vernacularName: 'Cebuano', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ilo', name: 'Iloko', vernacularName: 'Iloko', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'hil', name: 'Hiligaynon', vernacularName: 'Hiligaynon', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'war', name: 'Waray', vernacularName: 'Winaray', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'pam', name: 'Pampanga', vernacularName: 'Kapampangan', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'bcl', name: 'Bicol', vernacularName: 'Bicol', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'jv', name: 'Javanese', vernacularName: 'Jawa', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'su', name: 'Sundanese', vernacularName: 'Basa Sunda', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'fj', name: 'Fijian', vernacularName: 'vakaViti', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'sm', name: 'Samoan', vernacularName: 'Gagana Samoa', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'to', name: 'Tongan', vernacularName: 'lea faka-Tonga', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'mi', name: 'Maori', vernacularName: 'Te Reo Māori', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'haw', name: 'Hawaiian', vernacularName: 'ʻŌlelo Hawaiʻi', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ht', name: 'Haitian Creole', vernacularName: 'Kreyòl ayisyen', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'gug', name: 'Guarani', vernacularName: 'guarani', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ay', name: 'Aymara', vernacularName: 'Aymara', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'qu', name: 'Quechua', vernacularName: 'Runasimi', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'hmn', name: 'Hmong', vernacularName: 'Hmoob Dawb', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ase', name: 'American Sign Language', vernacularName: 'American Sign Language', script: 'ROMAN', direction: 'ltr', isSignLanguage: true },
    { code: 'bfi', name: 'British Sign Language', vernacularName: 'British Sign Language', script: 'ROMAN', direction: 'ltr', isSignLanguage: true },
    { code: 'fsl', name: 'French Sign Language', vernacularName: 'Langue des signes française', script: 'ROMAN', direction: 'ltr', isSignLanguage: true },
    { code: 'gsg', name: 'German Sign Language', vernacularName: 'Deutsche Gebärdensprache', script: 'ROMAN', direction: 'ltr', isSignLanguage: true },
    { code: 'jsl', name: 'Japanese Sign Language', vernacularName: '日本手話', script: 'JAPANESE', direction: 'ltr', isSignLanguage: true },
    { code: 'kvk', name: 'Korean Sign Language', vernacularName: '한국 수어', script: 'KOREAN', direction: 'ltr', isSignLanguage: true },
    { code: 'psp', name: 'Filipino Sign Language', vernacularName: 'Filipino Sign Language', script: 'ROMAN', direction: 'ltr', isSignLanguage: true },
];

// Simple lookup for dropdown display
export const LANGUAGE_OPTIONS = LANGUAGES.map(l => ({
    code: l.code,
    name: `${l.name} (${l.vernacularName})`
}));
