/**
 * Comprehensive language list including regional dialects and user-requested languages
 */

export interface Language {
    code: string;
    name: string;
    vernacularName: string;
    script: string;
    direction: 'ltr' | 'rtl';
    isSignLanguage: boolean;
}

export const LANGUAGES: Language[] = [
    { code: 'ab', name: 'Abkhaz', vernacularName: 'Аҧсуа бызшәа', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'ace', name: 'Acehnese', vernacularName: 'Bahsa Acèh', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ach', name: 'Acholi', vernacularName: 'Luo', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'aa', name: 'Afar', vernacularName: 'Qafaraf', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'af', name: 'Afrikaans', vernacularName: 'Afrikaans', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'sq', name: 'Albanian', vernacularName: 'Shqip', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'alz', name: 'Alur', vernacularName: 'Alur', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'am', name: 'Amharic', vernacularName: 'አማርኛ', script: 'ETHIOPIC', direction: 'ltr', isSignLanguage: false },
    { code: 'ar', name: 'Arabic', vernacularName: 'العربية', script: 'ARABIC', direction: 'rtl', isSignLanguage: false },
    { code: 'hy', name: 'Armenian', vernacularName: 'Հայերեն', script: 'ARMENIAN', direction: 'ltr', isSignLanguage: false },
    { code: 'as', name: 'Assamese', vernacularName: 'অসমীয়া', script: 'BENGALI', direction: 'ltr', isSignLanguage: false },
    { code: 'av', name: 'Avar', vernacularName: 'авар мацӀ', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'awa', name: 'Awadhi', vernacularName: 'अवधी', script: 'DEVANAGARI', direction: 'ltr', isSignLanguage: false },
    { code: 'ay', name: 'Aymara', vernacularName: 'Aymar aru', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'az', name: 'Azerbaijani', vernacularName: 'Azərbaycanca', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ban', name: 'Balinese', vernacularName: 'Basa Bali', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'bal', name: 'Baluchi', vernacularName: 'بلوچی', script: 'ARABIC', direction: 'rtl', isSignLanguage: false },
    { code: 'bm', name: 'Bambara', vernacularName: 'Bamanankan', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'bci', name: 'Baoulé', vernacularName: 'Wawle', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ba', name: 'Bashkir', vernacularName: 'башҡорт теле', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'eu', name: 'Basque', vernacularName: 'Euskara', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'btx', name: 'Batak Karo', vernacularName: 'Karo', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'bts', name: 'Batak Simalungun', vernacularName: 'Simalungun', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'bbc', name: 'Batak Toba', vernacularName: 'Toba', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'be', name: 'Belarusian', vernacularName: 'беларуская', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'bem', name: 'Bemba', vernacularName: 'Chibemba', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'bn', name: 'Bengali', vernacularName: 'বাংলা', script: 'BENGALI', direction: 'ltr', isSignLanguage: false },
    { code: 'bew', name: 'Betawi', vernacularName: 'Betawi', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'bho', name: 'Bhojpuri', vernacularName: 'भोजपुरी', script: 'DEVANAGARI', direction: 'ltr', isSignLanguage: false },
    { code: 'bcl', name: 'Bikol', vernacularName: 'Bicol', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'bs', name: 'Bosnian', vernacularName: 'bosanski', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'br', name: 'Breton', vernacularName: 'Brezhoneg', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'bg', name: 'Bulgarian', vernacularName: 'български', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'bua', name: 'Buryat', vernacularName: 'буряад хэлэн', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'yue', name: 'Chinese Cantonese', vernacularName: '廣東話', script: 'CHINESE', direction: 'ltr', isSignLanguage: false },
    { code: 'ca', name: 'Catalan', vernacularName: 'català', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ceb', name: 'Cebuano', vernacularName: 'Cebuano', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ch', name: 'Chamorro', vernacularName: 'Finu\' Chamoru', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ce', name: 'Chechen', vernacularName: 'нохчийн мотт', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'ny', name: 'Chichewa', vernacularName: 'Chichewa', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'zh-CN', name: 'Chinese (Simplified)', vernacularName: '中文简体', script: 'CHINESE', direction: 'ltr', isSignLanguage: false },
    { code: 'zh-TW', name: 'Chinese (Traditional)', vernacularName: '中文繁體', script: 'CHINESE', direction: 'ltr', isSignLanguage: false },
    { code: 'chk', name: 'Chuukese', vernacularName: 'Chuuk', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'cv', name: 'Chuvash', vernacularName: 'чӑваш чӗлхи', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'co', name: 'Corsican', vernacularName: 'Corsu', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'crh-Cyrl', name: 'Crimean Tatar (Cyrillic)', vernacularName: 'къырымтатарджа', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'crh-Latn', name: 'Crimean Tatar (Latin)', vernacularName: 'Qırımtatarca', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'hr', name: 'Croatian', vernacularName: 'hrvatski', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'cs', name: 'Czech', vernacularName: 'čeština', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'da', name: 'Danish', vernacularName: 'Dansk', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'prs', name: 'Dari', vernacularName: 'دری', script: 'ARABIC', direction: 'rtl', isSignLanguage: false },
    { code: 'dv', name: 'Dhivehi', vernacularName: 'ދިވެހި', script: 'THAANA', direction: 'rtl', isSignLanguage: false },
    { code: 'din', name: 'Dinka', vernacularName: 'Thuɔŋjäŋ', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'doi', name: 'Dogri', vernacularName: 'डोगरी', script: 'DEVANAGARI', direction: 'ltr', isSignLanguage: false },
    { code: 'dom', name: 'Dombe', vernacularName: 'Dombe', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'nl', name: 'Dutch', vernacularName: 'Nederlands', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'dyu', name: 'Dyula', vernacularName: 'Jula', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'dz', name: 'Dzongkha', vernacularName: 'རྫོང་ཁ་', script: 'TIBETAN', direction: 'ltr', isSignLanguage: false },
    { code: 'en-US', name: 'English (US)', vernacularName: 'English', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'eo', name: 'Esperanto', vernacularName: 'Esperanto', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'et', name: 'Estonian', vernacularName: 'eesti', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ee', name: 'Ewe', vernacularName: 'Èvègbe', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'fo', name: 'Faroese', vernacularName: 'føroyskt', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'fj', name: 'Fijian', vernacularName: 'vakaViti', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'tl-PH', name: 'Filipino (Tagalog)', vernacularName: 'Tagalog', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'fi', name: 'Finnish', vernacularName: 'suomi', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'fon', name: 'Fon', vernacularName: 'fɔ̀ngbè', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'fr-FR', name: 'French (France)', vernacularName: 'Français', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'fr-CA', name: 'French (Canada)', vernacularName: 'Français (Canada)', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'fy', name: 'Frisian', vernacularName: 'Frysk', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'fur', name: 'Friulian', vernacularName: 'furlan', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ff', name: 'Fulani', vernacularName: 'Fulfulde', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'gaa', name: 'Ga', vernacularName: 'Gã', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'gl', name: 'Galician', vernacularName: 'galego', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ka', name: 'Georgian', vernacularName: 'ქართული', script: 'GEORGIAN', direction: 'ltr', isSignLanguage: false },
    { code: 'de-DE', name: 'German', vernacularName: 'Deutsch', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'el', name: 'Greek', vernacularName: 'Ελληνική', script: 'GREEK', direction: 'ltr', isSignLanguage: false },
    { code: 'gn', name: 'Guarani', vernacularName: 'Avañe\'ẽ', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'gu', name: 'Gujarati', vernacularName: 'ગુજરાતી', script: 'GUJARATI', direction: 'ltr', isSignLanguage: false },
    { code: 'ht', name: 'Haitian Creole', vernacularName: 'Kreyòl ayisyen', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'csy', name: 'Hakha Chin', vernacularName: 'Laiholh', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ha', name: 'Hausa', vernacularName: 'Hausa', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'haw', name: 'Hawaiian', vernacularName: 'ʻŌlelo Hawaiʻi', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'he', name: 'Hebrew', vernacularName: 'עברית', script: 'HEBREW', direction: 'rtl', isSignLanguage: false },
    { code: 'hil', name: 'Hiligaynon', vernacularName: 'Hiligaynon', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'hi', name: 'Hindi', vernacularName: 'हिन्दी', script: 'DEVANAGARI', direction: 'ltr', isSignLanguage: false },
    { code: 'hmn', name: 'Hmong', vernacularName: 'Hmoob', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'hu', name: 'Hungarian', vernacularName: 'magyar', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'hrx', name: 'Hunsrik', vernacularName: 'Hunsrik', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'iba', name: 'Iban', vernacularName: 'Iban', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'is', name: 'Icelandic', vernacularName: 'íslenska', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ig', name: 'Igbo', vernacularName: 'Igbo', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ilo', name: 'Ilocano', vernacularName: 'Iloko', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'id', name: 'Indonesian', vernacularName: 'Indonesia', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'iu-Latn', name: 'Inuktut (Latin)', vernacularName: 'Inuktitut', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'iu-Syrl', name: 'Inuktut (Syllabics)', vernacularName: 'ᐃᓄᒃᑎᑐᑦ', script: 'INUKTITUT', direction: 'ltr', isSignLanguage: false },
    { code: 'ga', name: 'Irish', vernacularName: 'Gaeilge', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'it', name: 'Italian', vernacularName: 'Italiano', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'jam', name: 'Jamaican Patois', vernacularName: 'Jamaican Patois', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ja-JP', name: 'Japanese', vernacularName: '日本語', script: 'JAPANESE', direction: 'ltr', isSignLanguage: false },
    { code: 'jv', name: 'Javanese', vernacularName: 'Jawa', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'kac', name: 'Jingpo', vernacularName: 'Jinghpaw', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'kl', name: 'Kalaallisut', vernacularName: 'kalaallisut', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'kn', name: 'Kannada', vernacularName: 'ಕನ್ನಡ', script: 'KANNADA', direction: 'ltr', isSignLanguage: false },
    { code: 'kr', name: 'Kanuri', vernacularName: 'Kanuri', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'pam', name: 'Kapampangan', vernacularName: 'Kapampangan', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'kk', name: 'Kazakh', vernacularName: 'қазақ тілі', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'kha', name: 'Khasi', vernacularName: 'Khasi', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'km', name: 'Cambodian (Khmer)', vernacularName: 'ខ្មែរ', script: 'CAMBODIAN', direction: 'ltr', isSignLanguage: false },
    { code: 'cgg', name: 'Kiga', vernacularName: 'Rukiga', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'kg', name: 'Kongo', vernacularName: 'Kikongo', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'rw', name: 'Kinyarwanda', vernacularName: 'Ikinyarwanda', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ktub', name: 'Kituba', vernacularName: 'Kituba', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'kok', name: 'Kokborok', vernacularName: 'KokBorok', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'kv', name: 'Komi', vernacularName: 'коми кыв', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'kok-IN', name: 'Konkani', vernacularName: 'कोंकणी', script: 'DEVANAGARI', direction: 'ltr', isSignLanguage: false },
    { code: 'ko-KR', name: 'Korean', vernacularName: '한국어', script: 'KOREAN', direction: 'ltr', isSignLanguage: false },
    { code: 'kri', name: 'Krio', vernacularName: 'Krio', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ku', name: 'Kurdish (Kurmanji)', vernacularName: 'Kurdî', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ckb', name: 'Kurdish (Sorani)', vernacularName: 'سۆرانی', script: 'ARABIC', direction: 'rtl', isSignLanguage: false },
    { code: 'ky', name: 'Kyrgyz', vernacularName: 'кыргызча', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'lo', name: 'Laotian', vernacularName: 'ລາວ', script: 'LAOTIAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ltg', name: 'Latgalian', vernacularName: 'latgalīšu', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'la', name: 'Latin', vernacularName: 'Latina', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'lv', name: 'Latvian', vernacularName: 'latviešu', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'lij', name: 'Ligurian', vernacularName: 'Ligure', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'li', name: 'Limburgish', vernacularName: 'Limburgs', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ln', name: 'Lingala', vernacularName: 'Lingala', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'lt', name: 'Lithuanian', vernacularName: 'lietuvių', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'lmo', name: 'Lombard', vernacularName: 'Lumbaard', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'lg', name: 'Luganda', vernacularName: 'Luganda', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'luo', name: 'Luo', vernacularName: 'Dholuo', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'lb', name: 'Luxembourgish', vernacularName: 'Lëtzebuergesch', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'mk', name: 'Macedonian', vernacularName: 'македонски', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'mad', name: 'Madurese', vernacularName: 'Basa Madura', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'mai', name: 'Maithili', vernacularName: 'मैथिली', script: 'DEVANAGARI', direction: 'ltr', isSignLanguage: false },
    { code: 'mak', name: 'Makassar', vernacularName: 'Mangkasara', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'mg', name: 'Malagasy', vernacularName: 'Malagasy', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ms', name: 'Malay', vernacularName: 'Melayu', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ms-Arab', name: 'Malay (Jawi)', vernacularName: 'جاوي', script: 'ARABIC', direction: 'rtl', isSignLanguage: false },
    { code: 'ml', name: 'Malayalam', vernacularName: 'മലയാളം', script: 'MALAYALAM', direction: 'ltr', isSignLanguage: false },
    { code: 'mt', name: 'Maltese', vernacularName: 'Malti', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'mam', name: 'Mam', vernacularName: 'Qyol Mam', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'gv', name: 'Manx', vernacularName: 'Gaelg', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'mi', name: 'Maori', vernacularName: 'Te Reo Māori', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'mr', name: 'Marathi', vernacularName: 'मराठी', script: 'DEVANAGARI', direction: 'ltr', isSignLanguage: false },
    { code: 'mh', name: 'Marshallese', vernacularName: 'Kajin M̧ajyel', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'mwr', name: 'Marwadi', vernacularName: 'मारवाड़ी', script: 'DEVANAGARI', direction: 'ltr', isSignLanguage: false },
    { code: 'mfe', name: 'Mauritian Creole', vernacularName: 'Morisyen', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'mhr', name: 'Meadow Mari', vernacularName: 'олык марий', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'mni', name: 'Meiteilon (Manipuri)', vernacularName: 'মৈতেইলোন', script: 'BENGALI', direction: 'ltr', isSignLanguage: false },
    { code: 'min', name: 'Minang', vernacularName: 'Baso Minang', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'lus', name: 'Mizo', vernacularName: 'Mizo ṭawng', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'mn', name: 'Mongolian', vernacularName: 'монгол', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'my', name: 'Myanmar (Burmese)', vernacularName: 'မြန်မာ', script: 'MYANMAR', direction: 'ltr', isSignLanguage: false },
    { code: 'ncj', name: 'Nahuatl (Eastern Huasteca)', vernacularName: 'Mexicatlahtolli', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'nd', name: 'Ndau', vernacularName: 'Ndau', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'nbl', name: 'Ndebele (South)', vernacularName: 'isiNdebele', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'new', name: 'Nepalbhasa (Newari)', vernacularName: 'नेपाल भाषा', script: 'DEVANAGARI', direction: 'ltr', isSignLanguage: false },
    { code: 'ne', name: 'Nepali', vernacularName: 'नेपाली', script: 'DEVANAGARI', direction: 'ltr', isSignLanguage: false },
    { code: 'nko', name: 'NKo', vernacularName: 'ߒߞߏ', script: 'NKO', direction: 'rtl', isSignLanguage: false },
    { code: 'no', name: 'Norwegian', vernacularName: 'Norsk', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'nus', name: 'Nuer', vernacularName: 'Thok Nath', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'oc', name: 'Occitan', vernacularName: 'Occitan', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'or', name: 'Odia (Oriya)', vernacularName: 'ଓଡ଼ିଆ', script: 'ORIYA', direction: 'ltr', isSignLanguage: false },
    { code: 'om', name: 'Oromo', vernacularName: 'Oromoo', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'os', name: 'Ossetian', vernacularName: 'ирон', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'pag', name: 'Pangasinan', vernacularName: 'Pangasinan', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'pap', name: 'Papiamento', vernacularName: 'Papiamentu', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ps', name: 'Pashto', vernacularName: 'پښتو', script: 'ARABIC', direction: 'rtl', isSignLanguage: false },
    { code: 'fa', name: 'Persian (Farsi)', vernacularName: 'فارسی', script: 'ARABIC', direction: 'rtl', isSignLanguage: false },
    { code: 'pl', name: 'Polish', vernacularName: 'polski', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'pt-BR', name: 'Portuguese (Brazil)', vernacularName: 'Português (Brasil)', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'pt-PT', name: 'Portuguese (Portugal)', vernacularName: 'Português', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'pa', name: 'Punjabi (Gurmukhi)', vernacularName: 'ਪੰਜਾਬੀ', script: 'GURMUKHI', direction: 'ltr', isSignLanguage: false },
    { code: 'pa-PK', name: 'Punjabi (Shahmukhi)', vernacularName: 'پنجابی', script: 'ARABIC', direction: 'rtl', isSignLanguage: false },
    { code: 'qu', name: 'Quechua', vernacularName: 'Runa Simi', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'kek', name: 'Qʼeqchiʼ', vernacularName: 'Q\'eqchi\'', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'rom', name: 'Romani', vernacularName: 'Romani čhib', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ro', name: 'Romanian', vernacularName: 'Română', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'rn', name: 'Rundi', vernacularName: 'Ikirundi', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ru', name: 'Russian', vernacularName: 'русский', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'se', name: 'Sami (North)', vernacularName: 'davvisámegiella', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'sm', name: 'Samoan', vernacularName: 'Gagana Samoa', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'sg', name: 'Sango', vernacularName: 'Sängö', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'sa', name: 'Sanskrit', vernacularName: 'संस्कृतम्', script: 'DEVANAGARI', direction: 'ltr', isSignLanguage: false },
    { code: 'sat-Latn', name: 'Santali (Latin)', vernacularName: 'Santali', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'sat-Olck', name: 'Santali (Ol Chiki)', vernacularName: 'ᱥᱟᱱᱛᱟᱲᱤ', script: 'OL_CHIKI', direction: 'ltr', isSignLanguage: false },
    { code: 'gd', name: 'Scots Gaelic', vernacularName: 'Gàidhlig', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'nso', name: 'Sepedi', vernacularName: 'Sesotho sa Leboa', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'sr', name: 'Serbian', vernacularName: 'српски', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'st', name: 'Sesotho', vernacularName: 'Sesotho', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'crs', name: 'Seychellois Creole', vernacularName: 'Kreol Seselwa', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'shn', name: 'Shan', vernacularName: 'လိၵ်ႈတႆး', script: 'MYANMAR', direction: 'ltr', isSignLanguage: false },
    { code: 'sn', name: 'Shona', vernacularName: 'chiShona', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'scn', name: 'Sicilian', vernacularName: 'sicilianu', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'szl', name: 'Silesian', vernacularName: 'ślōnskŏ gŏdka', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'sd', name: 'Sindhi', vernacularName: 'سنڌي', script: 'ARABIC', direction: 'rtl', isSignLanguage: false },
    { code: 'si', name: 'Sinhala', vernacularName: 'සිංහල', script: 'SINHALA', direction: 'ltr', isSignLanguage: false },
    { code: 'sk', name: 'Slovak', vernacularName: 'slovenčina', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'sl', name: 'Slovenian', vernacularName: 'slovenščina', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'so', name: 'Somali', vernacularName: 'Soomaaliga', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'es-ES', name: 'Spanish', vernacularName: 'Español', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'su', name: 'Sundanese', vernacularName: 'Basa Sunda', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'sus', name: 'Susu', vernacularName: 'Susu', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'sw', name: 'Swahili', vernacularName: 'Kiswahili', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ss', name: 'Swati', vernacularName: 'siSwati', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'sv', name: 'Swedish', vernacularName: 'Svenska', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ty', name: 'Tahitian', vernacularName: 'Reo Tahiti', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'tg', name: 'Tajik', vernacularName: 'тоҷикӣ', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'tzm', name: 'Tamazight', vernacularName: 'Tamazight', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'tzm-Tfng', name: 'Tamazight (Tifinagh)', vernacularName: 'ⵜⴰⵎⴰⵣⵉⵖⵜ', script: 'TIFINAGH', direction: 'ltr', isSignLanguage: false },
    { code: 'ta', name: 'Tamil', vernacularName: 'தமிழ்', script: 'TAMIL', direction: 'ltr', isSignLanguage: false },
    { code: 'tt', name: 'Tatar', vernacularName: 'татарча', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'te', name: 'Telugu', vernacularName: 'తెలుగు', script: 'TELUGU', direction: 'ltr', isSignLanguage: false },
    { code: 'tet', name: 'Tetum', vernacularName: 'Lia-Tetun', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'th', name: 'Thai', vernacularName: 'ไทย', script: 'THAI', direction: 'ltr', isSignLanguage: false },
    { code: 'bo', name: 'Tibetan', vernacularName: 'བོད་སྐད་', script: 'TIBETAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ti', name: 'Tigrinya', vernacularName: 'ትግርኛ', script: 'ETHIOPIC', direction: 'ltr', isSignLanguage: false },
    { code: 'tiv', name: 'Tiv', vernacularName: 'Tiv', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'tpi', name: 'Tok Pisin', vernacularName: 'Tok Pisin', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'to', name: 'Tongan', vernacularName: 'lea faka-Tonga', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'lua', name: 'Tshiluba', vernacularName: 'Tshiluba', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'ts', name: 'Tsonga', vernacularName: 'Xitsonga', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'tn', name: 'Tswana', vernacularName: 'Setswana', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'tcy', name: 'Tulu', vernacularName: 'ತುಳು', script: 'KANNADA', direction: 'ltr', isSignLanguage: false },
    { code: 'tum', name: 'Tumbuka', vernacularName: 'chiTumbuka', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'tr', name: 'Turkish', vernacularName: 'Türkçe', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'tk', name: 'Turkmen', vernacularName: 'türkmençe', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'tyv', name: 'Tuvan', vernacularName: 'тыва дыл', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'tw', name: 'Twi', vernacularName: 'Twi', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'udm', name: 'Udmurt', vernacularName: 'удмурт кыл', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'uk', name: 'Ukrainian', vernacularName: 'українська', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'ur', name: 'Urdu', vernacularName: 'اردو', script: 'ARABIC', direction: 'rtl', isSignLanguage: false },
    { code: 'ug', name: 'Uyghur', vernacularName: 'ئۇيغۇرچە', script: 'ARABIC', direction: 'rtl', isSignLanguage: false },
    { code: 'uz', name: 'Uzbek', vernacularName: 'O\'zbekcha', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 've', name: 'Venda', vernacularName: 'Tshivenda', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'vec', name: 'Venetian', vernacularName: 'vèneto', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'vi', name: 'Vietnamese', vernacularName: 'Tiếng Việt', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'war', name: 'Waray', vernacularName: 'Winaray', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'cy', name: 'Welsh', vernacularName: 'Cymraeg', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'wo', name: 'Wolof', vernacularName: 'Wolof', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'xh', name: 'Xhosa', vernacularName: 'isiXhosa', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'sah', name: 'Yakut', vernacularName: 'саха тыла', script: 'CYRILLIC', direction: 'ltr', isSignLanguage: false },
    { code: 'yi', name: 'Yiddish', vernacularName: 'ייִדיש', script: 'HEBREW', direction: 'rtl', isSignLanguage: false },
    { code: 'yo', name: 'Yoruba', vernacularName: 'Yorùbá', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'yua', name: 'Yucatec Maya', vernacularName: 'Maaya t\'aan', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'zap', name: 'Zapotec', vernacularName: 'Diidxazá', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
    { code: 'zu', name: 'Zulu', vernacularName: 'isiZulu', script: 'ROMAN', direction: 'ltr', isSignLanguage: false },
].sort((a, b) => a.name.localeCompare(b.name)) as Language[];

// Simple lookup for dropdown display
export const LANGUAGE_OPTIONS = LANGUAGES.map(l => ({
    code: l.code,
    name: `${l.name} (${l.vernacularName})`
})).sort((a, b) => a.name.localeCompare(b.name));
